### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by refugedesigns** [angelsolaorbaiceta/fe-fwk-book#162] opened 2023-09-09 06:44 UTC
It would be great to publish part 2 of this where you included typescript support and namespace support and turn the framework into a full blown production ready framework.

**Comment by angelsolaorbaiceta** [comment] 2023-09-09 09:39
Hi @refugedesigns , this is the plan (kind of). Not sure if we can take it as far as being "production ready," but the goal is to take it as close as possible while maintaining the project a valuable learning source. The priority is for it to be as simple as possible for learners to easily follow, but at the same time to make it complex enough so that it is close to what real frameworks are.

If you don't mind I'll remove the "bug" label, as this is more of a suggestion—not a bug in the implementation—and close the issue, as this is already part of the plan and no further action is required.

**Closed by angelsolaorbaiceta** 2023-09-09 09:39 UTC

**Comment by refugedesigns** [comment] 2023-09-09 09:44
sure @angelsolaorbaiceta  you can remove the bug label or turn it into suggestion label. I posted it before realizing the tag was a bug label, sorry for that and thanks for your reply. I am actually looking forward to learning a lot from your book since I have always tried hard to contribute to open source projects, but don't really understand the code base. I know this will give me enough understanding to give me the start.

**Comment by angelsolaorbaiceta** [comment] 2023-09-09 10:30
That's completely fine! :) 

I hope the book helps you in your learning journey and gives you the confidence you need to collaborate in OS projects. Looking forward to your contributions!
